channels:
  - conda-forge
  - bioconda
  - ecoevoinfo
  - defaults

package:
  name: autostreamtree
  version: "$VERSION"

source:
  path: ../ 

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
  - python >=3.10
  - pip
  - setuptools
  - perl
  - pytest
  - numpy
  - pandas >2
  - matplotlib
  - seaborn
  - geopandas
  - pyogrio
  - sortedcontainers
  - momepy
  - networkx >3
  - mantel
  - pysam
  - pyarrow
  - pdoc3
  - scikit-learn >1

build:
  noarch: python

about:
  home: "https://github.com/tkchafin/autostreamtree"
  license: "GPLv3"
  summary: "A package for fitting genetic distances to spatial networks"
